version: "3.9"
networks:
  neo4j-network:
    driver: bridge
  app-network:
    driver: bridge
services:
  my_app:
    build: .
    env_file:
      - .env
  # neo4j:
  #   image: bitnami/neo4j:latest
  #   networks:
  #     - neo4j-network
  #   ports:
  #     - "7474:7474"
  #     - "7473:7473"
  #     - "7687:7687"
  redis-redisjson:
    container_name:  redis-redisjson
    hostname:  redis-redisjson
    image: redislabs/rejson
    ports: 
      - 6379:6379
  
  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - 6379:6379
  #   command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${USERNAME}:${PASSWORD}@mongo:27017/
  # cassandra:
  #   image: cassandra:4.0
  #   ports:
  #     - 9042:9042
  #   volumes:
  #     - ~/apps/cassandra:/var/lib/cassandra
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=citizix
volumes:
  cache:
    driver: local
