version: "3.9"
networks:
  app-network:
    driver: bridge
services:
  # neo4j:
  #   image: bitnami/neo4j:latest
  #   networks:
  #     - neo4j-network
  #   ports:
  #     - "7474:7474"
  #     - "7473:7473"
  #     - "7687:7687"
  redis-redisjson:
    container_name:  redis-redisjson
    hostname:  redis-redisjson
    image: redislabs/rejson
    ports: 
      - 6379:6379
  
  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - 6379:6379
  #   command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    env_file:
      - .env
    environment:
      COUCHDB_USER: ${USERNAME}
      COUCHDB_PASSWORD: ${PASSWORD}
volumes:
  cache:
    driver: local
